### ISSUE TITLE
修改为自己的数据集类别

### ISSUE THREAD

**Issue by ZRJL** [derek285/yolov4_deep_sort_pytorch#4]
楼主你好，我想请问下怎么在代码里修改为我自己检测数据集的类？数据集是自己做的。

**Comment by derek285** [comment]
> 楼主你好，我想请问下怎么在代码里修改为我自己检测数据集的类？数据集是自己做的。

其实就是用自己的数据训练检测器YOLOV4， 然后模型等做好替换，类型的话修改文件coco.data和coco.names
